apiVersion: v1
kind: ReplicationController
metadata: 
 name: app-rc
 labels: 
  app: app
spec: 
 replicas: 3
 selector: 
  app: app
 template: 
  metadata: 
   name: app-pod
   labels: 
    app: app
  spec: 
   containers: 
    - name: nginx
      image: nginx 
