apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: app-cron-job
spec: 
 schedule: "*/1 * * * *" 
 jobTemplate: 
  spec: 
   completions: 3
   parallelism: 3
   template:   
    spec: 
     containers:  
      - name: nginx
        image: nginx
        command: ["expr","3","+","2"]
     restartPolicy: Never 
