apiVersion: v1
kind: PersistentVolume
metadata: 
 name: pv01
spec: 
 accessModes: 
  - ReadWriteMany
 capacity:  
   storage: 100Mi
 hostPath: 
  path: /data
  type: Directory
 storageClassName: standard
 persistentVolumeReclaimPolicy: Delete
    
